# Generated by Django 6.1.1 on 2026-09-22 17:54

import apps.news.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('url', models.URLField(max_length=500, unique=True, verbose_name='RSS/Atom URL')),
                ('category', models.CharField(choices=[('technology', 'Technology'), ('business', 'Business'), ('world', 'World'), ('science', 'Science'), ('health', 'Health'), ('sports', 'Sports'), ('culture', 'Culture'), ('other', 'Other')], default='other', max_length=40, verbose_name='default category')),
                ('language', models.CharField(default=apps.news.models.default_feed_language, help_text='ISO code: tr, en, de...', max_length=5, verbose_name='language')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('etag', models.CharField(blank=True, editable=False, max_length=255)),
                ('last_modified', models.CharField(blank=True, editable=False, max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='last synced at')),
            ],
            options={
                'verbose_name': 'feed',
                'verbose_name_plural': 'feeds',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000, unique=True, verbose_name='URL')),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('excerpt', models.TextField(blank=True, verbose_name='RSS excerpt')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                ('image_url', models.URLField(blank=True, max_length=1000, verbose_name='image')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='published at')),
                ('summary', models.JSONField(blank=True, default=list, verbose_name='summary points')),
                ('category', models.CharField(blank=True, choices=[('technology', 'Technology'), ('business', 'Business'), ('world', 'World'), ('science', 'Science'), ('health', 'Health'), ('sports', 'Sports'), ('culture', 'Culture'), ('other', 'Other')], db_index=True, max_length=40, verbose_name='category')),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=10, verbose_name='sentiment')),
                ('importance', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='importance (1-10)')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='tags')),
                ('enriched_at', models.DateTimeField(blank=True, null=True, verbose_name='enriched at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news.feed', verbose_name='feed')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
