# Generated by Django 6.1.1 on 2026-09-22 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='ad')),
                ('url', models.URLField(max_length=500, unique=True, verbose_name='RSS/Atom adresi')),
                ('category', models.CharField(default='diger', max_length=40, verbose_name='varsayılan kategori')),
                ('language', models.CharField(default='tr', help_text='ISO kodu: tr, en, de...', max_length=5, verbose_name='dil')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktif')),
                ('etag', models.CharField(blank=True, editable=False, max_length=255)),
                ('last_modified', models.CharField(blank=True, editable=False, max_length=255)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='son senkronizasyon')),
            ],
            options={
                'verbose_name': 'kaynak',
                'verbose_name_plural': 'kaynaklar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000, unique=True, verbose_name='adres')),
                ('title', models.CharField(max_length=500, verbose_name='başlık')),
                ('excerpt', models.TextField(blank=True, verbose_name='RSS özeti')),
                ('content', models.TextField(blank=True, verbose_name='içerik')),
                ('image_url', models.URLField(blank=True, max_length=1000, verbose_name='görsel')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='yayın tarihi')),
                ('summary', models.JSONField(blank=True, default=list, verbose_name='özet maddeleri')),
                ('category', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='kategori')),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Olumlu'), ('neutral', 'Nötr'), ('negative', 'Olumsuz')], max_length=10, verbose_name='duygu')),
                ('importance', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='önem (1-10)')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='etiketler')),
                ('enriched_at', models.DateTimeField(blank=True, null=True, verbose_name='zenginleştirme')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='eklenme')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news.feed', verbose_name='kaynak')),
            ],
            options={
                'verbose_name': 'haber',
                'verbose_name_plural': 'haberler',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
