# Generated by Django 6.1.1 on 2026-09-22 13:39

import django.db.models.deletion
from django.db import migrations, models


# v2.0.0'daki Türkçe kategori kodları -> İngilizce kodlar (etiketler artık .po dosyalarında çevriliyor)
CATEGORY_CODES = {
    "teknoloji": "technology",
    "ekonomi": "business",
    "dunya": "world",
    "bilim": "science",
    "saglik": "health",
    "spor": "sports",
    "kultur": "culture",
    "diger": "other",
}


def convert_categories(apps, schema_editor):
    for model_name in ("Feed", "Article"):
        model = apps.get_model("news", model_name)
        for old, new in CATEGORY_CODES.items():
            model.objects.filter(category=old).update(category=new)


def revert_categories(apps, schema_editor):
    for model_name in ("Feed", "Article"):
        model = apps.get_model("news", model_name)
        for old, new in CATEGORY_CODES.items():
            model.objects.filter(category=new).update(category=old)


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_search_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ['name'], 'verbose_name': 'feed', 'verbose_name_plural': 'feeds'},
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, choices=[('technology', 'Technology'), ('business', 'Business'), ('world', 'World'), ('science', 'Science'), ('health', 'Health'), ('sports', 'Sports'), ('culture', 'Culture'), ('other', 'Other')], db_index=True, max_length=40, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='article',
            name='enriched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='enriched at'),
        ),
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.TextField(blank=True, verbose_name='RSS excerpt'),
        ),
        migrations.AlterField(
            model_name='article',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news.feed', verbose_name='feed'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='importance',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='importance (1-10)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='published at'),
        ),
        migrations.AlterField(
            model_name='article',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=10, verbose_name='sentiment'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.JSONField(blank=True, default=list, verbose_name='summary points'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=500, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(max_length=1000, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('business', 'Business'), ('world', 'World'), ('science', 'Science'), ('health', 'Health'), ('sports', 'Sports'), ('culture', 'Culture'), ('other', 'Other')], default='other', max_length=40, verbose_name='default category'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='language',
            field=models.CharField(default='tr', help_text='ISO code: tr, en, de...', max_length=5, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last synced at'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='name',
            field=models.CharField(max_length=120, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='url',
            field=models.URLField(max_length=500, unique=True, verbose_name='RSS/Atom URL'),
        ),
        migrations.RunPython(convert_categories, revert_categories),
    ]
