# Generated by Django 6.1.1 on 2026-09-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ad soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='e-posta')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telefon')),
                ('message', models.TextField(verbose_name='mesaj')),
                ('consent_at', models.DateTimeField(verbose_name='KVKK onay zamanı')),
                ('status', models.CharField(choices=[('new', 'Yeni'), ('in_progress', 'İşlemde'), ('closed', 'Kapandı')], db_index=True, default='new', max_length=20, verbose_name='durum')),
                ('notes', models.TextField(blank=True, verbose_name='iç notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='oluşturulma')),
            ],
            options={
                'verbose_name': 'talep',
                'verbose_name_plural': 'talepler',
                'ordering': ['-created_at'],
            },
        ),
    ]
