# Generated by Django 6.1.1 on 2026-09-22 14:04

import apps.inquiries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='full name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='phone')),
                ('message', models.TextField(verbose_name='message')),
                ('language', models.CharField(default=apps.inquiries.models.default_language, max_length=10, verbose_name='language')),
                ('consent_at', models.DateTimeField(verbose_name='consent given at')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('closed', 'Closed')], db_index=True, default='new', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'inquiry',
                'verbose_name_plural': 'inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
