# Generated by Django 6.1.1 on 2026-09-22 13:39

import apps.inquiries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'inquiry', 'verbose_name_plural': 'inquiries'},
        ),
        migrations.AddField(
            model_name='inquiry',
            name='language',
            field=models.CharField(default=apps.inquiries.models.default_language, max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='consent_at',
            field=models.DateTimeField(verbose_name='consent given at'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='notes',
            field=models.TextField(blank=True, verbose_name='internal notes'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('closed', 'Closed')], db_index=True, default='new', max_length=20, verbose_name='status'),
        ),
    ]
