# Generated by Django 6.1.1 on 2026-09-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.CharField(max_length=40, unique=True, verbose_name='OSM kimliği')),
                ('name', models.CharField(max_length=255, verbose_name='ad')),
                ('category', models.CharField(db_index=True, max_length=60, verbose_name='kategori')),
                ('lat', models.FloatField(verbose_name='enlem')),
                ('lng', models.FloatField(verbose_name='boylam')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='adres')),
                ('phone', models.CharField(blank=True, max_length=60, verbose_name='telefon')),
                ('website', models.URLField(blank=True, max_length=500, verbose_name='web sitesi')),
                ('opening_hours', models.CharField(blank=True, max_length=255, verbose_name='çalışma saatleri')),
                ('tags', models.JSONField(blank=True, default=dict, verbose_name='OSM etiketleri')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
            ],
            options={
                'verbose_name': 'yer',
                'verbose_name_plural': 'yerler',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['lat', 'lng'], name='place_lat_lng_idx')],
            },
        ),
    ]
