# Generated by Django 6.1.1 on 2026-09-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.CharField(max_length=40, unique=True, verbose_name='OSM id')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('category', models.CharField(db_index=True, max_length=60, verbose_name='category')),
                ('lat', models.FloatField(verbose_name='latitude')),
                ('lng', models.FloatField(verbose_name='longitude')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='address')),
                ('phone', models.CharField(blank=True, max_length=60, verbose_name='phone')),
                ('website', models.URLField(blank=True, max_length=500, verbose_name='website')),
                ('opening_hours', models.CharField(blank=True, max_length=255, verbose_name='opening hours')),
                ('tags', models.JSONField(blank=True, default=dict, verbose_name='OSM tags')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'place',
                'verbose_name_plural': 'places',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['lat', 'lng'], name='place_lat_lng_idx')],
            },
        ),
    ]
