# Generated by Django 6.1.1 on 2026-09-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['name'], 'verbose_name': 'place', 'verbose_name_plural': 'places'},
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(db_index=True, max_length=60, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.FloatField(verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lng',
            field=models.FloatField(verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='place',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=255, verbose_name='opening hours'),
        ),
        migrations.AlterField(
            model_name='place',
            name='osm_id',
            field=models.CharField(max_length=40, unique=True, verbose_name='OSM id'),
        ),
        migrations.AlterField(
            model_name='place',
            name='phone',
            field=models.CharField(blank=True, max_length=60, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='place',
            name='tags',
            field=models.JSONField(blank=True, default=dict, verbose_name='OSM tags'),
        ),
        migrations.AlterField(
            model_name='place',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='place',
            name='website',
            field=models.URLField(blank=True, max_length=500, verbose_name='website'),
        ),
    ]
