# Generated by Django 6.1.1 on 2026-09-22 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='ad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to=settings.AUTH_USER_MODEL, verbose_name='sahibi')),
            ],
            options={
                'verbose_name': 'pano',
                'verbose_name_plural': 'panolar',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='başlık')),
                ('description', models.TextField(blank=True, verbose_name='açıklama')),
                ('status', models.CharField(choices=[('todo', 'Yapılacak'), ('doing', 'Yapılıyor'), ('done', 'Tamamlandı')], default='todo', max_length=10, verbose_name='durum')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='sıra')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='güncellenme')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='kanban.board', verbose_name='pano')),
            ],
            options={
                'verbose_name': 'kart',
                'verbose_name_plural': 'kartlar',
                'ordering': ['status', 'position', 'id'],
                'indexes': [models.Index(fields=['board', 'status', 'position'], name='kanban_card_order_idx')],
            },
        ),
    ]
