# Generated by Django 6.1.1 on 2026-09-22 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(db_index=True, max_length=50, verbose_name='görev')),
                ('status', models.CharField(choices=[('queued', 'Sırada'), ('running', 'Çalışıyor'), ('success', 'Başarılı'), ('failed', 'Hatalı')], default='queued', max_length=10, verbose_name='durum')),
                ('items', models.PositiveIntegerField(default=0, verbose_name='öge sayısı')),
                ('message', models.TextField(blank=True, verbose_name='mesaj')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='oluşturulma')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='başlangıç')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='bitiş')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='başlatan')),
            ],
            options={
                'verbose_name': 'senkronizasyon',
                'verbose_name_plural': 'senkronizasyonlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
