# Generated by Django 6.1.1 on 2026-09-22 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(db_index=True, max_length=50, verbose_name='job')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=10, verbose_name='status')),
                ('items', models.PositiveIntegerField(default=0, verbose_name='items')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finished at')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='triggered by')),
            ],
            options={
                'verbose_name': 'sync run',
                'verbose_name_plural': 'sync runs',
                'ordering': ['-created_at'],
            },
        ),
    ]
