# Generated by Django 6.1.1 on 2026-09-22 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syncrun',
            options={'ordering': ['-created_at'], 'verbose_name': 'sync run', 'verbose_name_plural': 'sync runs'},
        ),
        migrations.AlterField(
            model_name='syncrun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='syncrun',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='finished at'),
        ),
        migrations.AlterField(
            model_name='syncrun',
            name='items',
            field=models.PositiveIntegerField(default=0, verbose_name='items'),
        ),
        migrations.AlterField(
            model_name='syncrun',
            name='job',
            field=models.CharField(db_index=True, max_length=50, verbose_name='job'),
        ),
        migrations.AlterField(
            model_name='syncrun',
            name='message',
            field=models.TextField(blank=True, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='syncrun',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='started at'),
        ),
        migrations.AlterField(
            model_name='syncrun',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='syncrun',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='triggered by'),
        ),
    ]
